enum TipoEdicaoCor{
  COR_APP_BAR,
  COR_TITULO_APP_BAR,
  COR_BOTAO_ADICIONAR_TAREFA,
  COR_ICONE_ADICIONAR_TAREFA,
  COR_ICONE_TAREFA_NAO_CONCLUIDA,
  COR_FUNDO_TAREFA_NAO_CONCLUIDA,
  COR_ICONE_TAREFA_CONCLUIDA,
  COR_FUNDO_TAREFA_CONCLUIDA
}

const Map<TipoEdicaoCor,String> TipoEdicaoCorSelecao = {
  TipoEdicaoCor.COR_APP_BAR: "CORAPPBAR",
  TipoEdicaoCor.COR_TITULO_APP_BAR: "CORTITULOAPPBAR",
  TipoEdicaoCor.COR_BOTAO_ADICIONAR_TAREFA: "CORBOTAOADICIONARTAREFA",
  TipoEdicaoCor.COR_ICONE_ADICIONAR_TAREFA: "CORICONEADICIONARTAREFA",
  TipoEdicaoCor.COR_ICONE_TAREFA_NAO_CONCLUIDA: "CORICONETAREFANAOCONCLUIDA",
  TipoEdicaoCor.COR_FUNDO_TAREFA_NAO_CONCLUIDA:  "CORFUNDOTAREFANAOCONCLUIDA",
  TipoEdicaoCor.COR_ICONE_TAREFA_CONCLUIDA: "CORICONETAREFACONCLUIDA",
  TipoEdicaoCor.COR_FUNDO_TAREFA_CONCLUIDA: "CORFUNDOTAREFACONCLUIDA"
};