enum TipoEdicaoCor{
  COR_APP_BAR,
  COR_TITULO_APP_BAR,
  COR_BOTAO_ADICIONAR_TAREFA,
  COR_ICONE_ADICIONAR_TAREFA,
  COR_ICONE_TAREFA_NAO_CONCLUIDA,
  COR_FUNDO_TAREFA_NAO_CONCLUIDA,
  COR_ICONE_TAREFA_CONCLUIDA,
  COR_FUNDO_TAREFA_CONCLUIDA
}

const Map<TipoEdicaoCor,String> TipoEdicaoCorSelecao = {
  TipoEdicaoCor.COR_APP_BAR: "CORAPPBAR",
  TipoEdicaoCor.COR_TITULO_APP_BAR: "CORTITULOAPPBAR",
  TipoEdicaoCor.COR_BOTAO_ADICIONAR_TAREFA: "BADICIONARTAREFA",
  TipoEdicaoCor.COR_ICONE_ADICIONAR_TAREFA: "IADICIONARTAREFA",
  TipoEdicaoCor.COR_ICONE_TAREFA_NAO_CONCLUIDA: "ITAREFANCONCLUIDA",
  TipoEdicaoCor.COR_FUNDO_TAREFA_NAO_CONCLUIDA:  "FUNDOTAREFANCONCLUIDA",
  TipoEdicaoCor.COR_ICONE_TAREFA_CONCLUIDA: "ITAREFACONCLUIDA",
  TipoEdicaoCor.COR_FUNDO_TAREFA_CONCLUIDA: "FTAREFACONCLUIDA"
};